//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMU7800.SL.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMU7800.SL.Model.Repository.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] actionmn {
            get {
                object obj = ResourceManager.GetObject("actionmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ADVNTURE {
            get {
                object obj = ResourceManager.GetObject("ADVNTURE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ASTEROID {
            get {
                object obj = ResourceManager.GetObject("ASTEROID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Asteroids {
            get {
                object obj = ResourceManager.GetObject("Asteroids", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Berzerk {
            get {
                object obj = ResourceManager.GetObject("Berzerk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Breakout {
            get {
                object obj = ResourceManager.GetObject("Breakout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Choprcmd {
            get {
                object obj = ResourceManager.GetObject("Choprcmd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Combat {
            get {
                object obj = ResourceManager.GetObject("Combat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cosmcark {
            get {
                object obj = ResourceManager.GetObject("Cosmcark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Darkchambers {
            get {
                object obj = ResourceManager.GetObject("Darkchambers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Demonatk {
            get {
                object obj = ResourceManager.GetObject("Demonatk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Digdug {
            get {
                object obj = ResourceManager.GetObject("Digdug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Donkeykong {
            get {
                object obj = ResourceManager.GetObject("Donkeykong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Donkeykongjr {
            get {
                object obj = ResourceManager.GetObject("Donkeykongjr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Drgnfire {
            get {
                object obj = ResourceManager.GetObject("Drgnfire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Frogger {
            get {
                object obj = ResourceManager.GetObject("Frogger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Galaga {
            get {
                object obj = ResourceManager.GetObject("Galaga", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Impossiblemission {
            get {
                object obj = ResourceManager.GetObject("Impossiblemission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Joust {
            get {
                object obj = ResourceManager.GetObject("Joust", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mariobros {
            get {
                object obj = ResourceManager.GetObject("Mariobros", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MISSCOMM {
            get {
                object obj = ResourceManager.GetObject("MISSCOMM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mspacman {
            get {
                object obj = ResourceManager.GetObject("Mspacman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OYSTR29 {
            get {
                object obj = ResourceManager.GetObject("OYSTR29", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PACCOLL {
            get {
                object obj = ResourceManager.GetObject("PACCOLL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Pacman {
            get {
                object obj = ResourceManager.GetObject("Pacman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Robotron2084 {
            get {
                object obj = ResourceManager.GetObject("Robotron2084", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SI7800 {
            get {
                object obj = ResourceManager.GetObject("SI7800", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SPCINVAD {
            get {
                object obj = ResourceManager.GetObject("SPCINVAD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Summergames {
            get {
                object obj = ResourceManager.GetObject("Summergames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wintergames {
            get {
                object obj = ResourceManager.GetObject("Wintergames", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
